apiVersion: v1
kind: Pod
metadata:
  labels:
    owner: me.agilebank.demo
  name: resource-beta-0
spec:
  containers:
  - args:
    - run
    - --server
    - --addr=localhost:8080
    image: nginx:1.14.2:0.9.2
    name: opa
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
