apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: disallowed-storage-class
  namespace: ''
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-beta-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: disallowed-storage-class
  volumeMode: Filesystem
