apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  containers:
  - image: nginxinc/nginx-unprivileged:latest
    name: container-alpha
    securityContext:
      seccompProfile:
        type: RuntimeDefault
