apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx: unconfined
  labels:
    app: app-beta
  name: resource-beta
spec:
  containers:
  - image: nginx
    name: container-beta
