apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-ai-bench/expected: alpha
    k8s-ai-bench/inventory: "false"
    k8s-ai-bench/task: block-loadbalancer-services
  name: resource-alpha-01
  namespace: gk-block-loadbalancer-services
spec:
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
