apiVersion: test.gatekeeper.sh/v1alpha1
kind: Suite
metadata:
  name: unique-service-selector
tests:
- cases:
  - assertions:
    - violations: "no"
    inventory: null
    name: example-allowed
    object: artifacts/alpha-01.yaml
  - assertions:
    - violations: "yes"
    inventory:
    - artifacts/inventory-01.yaml
    name: example-disallowed
    object: artifacts/beta-01.yaml
  constraint: constraint.yaml
  name: unique-service-selector
  template: template.yaml
