apiVersion: v1
kind: Pod
metadata:
  name: resource-alpha
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 1h
    image: busybox
    name: container-alpha
    volumeMounts:
    - mountPath: /data/demo
      name: fsgroup-demo-vol
  securityContext:
    fsGroup: 500
  volumes:
  - emptyDir: {}
    name: fsgroup-demo-vol
