apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  containers:
  - image: nginx
    name: container-alpha
    volumeMounts:
    - mountPath: /test
      name: test-volume
      readOnly: true
  volumes:
  - flexVolume:
      driver: example/lvm
    name: test-volume
