apiVersion: v1
kind: Pod
metadata:
  name: resource-beta
spec:
  containers:
  - image: registry.k8s.io/kustomize/kustomize:v3.8.9
    name: container-beta
  initContainers:
  - image: k8s.gcr.io/kustomize/kustomize:v3.8.9
    name: init-container-beta
