apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-ai-bench/expected: beta
    k8s-ai-bench/inventory: "false"
    k8s-ai-bench/task: must-have-key
    taco: is-great
  name: resource-beta-01
  namespace: gk-must-have-key
spec:
  containers:
  - image: nginx
    name: nginx
