apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-beta
  name: resource-beta
spec:
  containers:
  - image: nginx
    name: container-beta
    securityContext:
      procMount: Unmasked
  hostUsers: false
