apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/container-alpha: localhost/custom
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  containers:
  - image: nginx
    name: container-alpha
