apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-beta
  name: resource-beta
spec:
  containers:
  - image: nginx
    name: container-beta
  securityContext:
    sysctls:
    - name: kernel.msgmax
      value: '65536'
    - name: net.core.somaxconn
      value: '1024'
