apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  containers:
  - image: nginx
    name: container-alpha
  securityContext:
    sysctls:
    - name: net.core.somaxconn
      value: '1024'
