apiVersion: v1
kind: Pod
metadata:
  name: resource-beta
spec:
  containers:
  - args:
    - run
    - --server
    - --addr=localhost:8080
    image: openpolicyagent/opa:0.9.2
    name: container-beta
    resources:
      limits:
        memory: 2Gi
