apiVersion: v1
kind: Pod
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  containers:
  - image: nginxinc/nginx-unprivileged:latest
    name: container-alpha
