apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-beta
  name: resource-beta
spec:
  containers:
  - image: nginx
    name: container-beta
    securityContext:
      seLinuxOptions:
        level: s1:c234,c567
        role: sysadm_r
        type: svirt_lxc_net_t
        user: sysadm_u
