apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-ai-bench/expected: beta
    k8s-ai-bench/inventory: "false"
    k8s-ai-bench/task: unique-service-selector
  name: resource-beta-01
  namespace: gk-unique-service-selector
spec:
  ports:
  - port: 443
  selector:
    key: value
