setup: setup.sh
cleanup: cleanup.sh
difficulty: medium
expect:
- contains: VIOLATING:.*resource-beta.*
  notContains: resource-alpha
script:
- prompt: 'Could you please check the gk-test-014 namespace for any Ingress resources
    that are missing a TLS configuration or don''t have the ''kubernetes.io/ingress.allow-http''
    annotation explicitly set to ''false''?


    If you find any, list them in this format:

    VIOLATING: resource_name, resource_name


    Otherwise, just output:

    VIOLATING: none'
