apiVersion: v1
kind: Pod
metadata:
  name: resource-beta
spec:
  containers:
  - image: nginx:latest
    livenessProbe: null
    name: container-beta
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /tmp/cache
      name: cache-volume
  - args:
    - python
    - -m
    - http.server
    - '8080'
    image: python:3.9-alpine
    name: container-beta-1
    ports:
    - containerPort: 8080
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      tcpSocket:
        port: 8080
  volumes:
  - emptyDir: {}
    name: cache-volume
