apiVersion: v1
kind: Pod
metadata:
  labels:
    k8s-ai-bench/expected: alpha
    k8s-ai-bench/inventory: "false"
    k8s-ai-bench/task: allowed-repos
  name: resource-alpha-01
  namespace: gk-allowed-repos
spec:
  containers:
  - args:
    - run
    - --server
    - --addr=localhost:8080
    image: openpolicyagent/opa:0.9.2
    name: opa
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
