apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    k8s-ai-bench/expected: beta
    k8s-ai-bench/inventory: "false"
    k8s-ai-bench/task: pod-disruption-budget
  name: resource-beta-02
  namespace: gk-pod-disruption-budget
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      example: disallowed-deployment
  template:
    metadata:
      labels:
        app: nginx
        example: disallowed-deployment
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
