apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-beta
  name: resource-beta
spec:
  containers:
  - image: nginxinc/nginx-unprivileged:latest
    name: container-beta
  hostIPC: true
  hostPID: true
