apiVersion: v1
kind: Pod
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: unconfined
  labels:
    app: app-beta
  name: resource-beta
spec:
  containers:
  - image: nginx
    name: container-beta
