apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  namespace: ''
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resource-alpha-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeMode: Filesystem

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: somestorageclass
  namespace: ''
provisioner: kubernetes.io/no-provisioner
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-alpha-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-alpha
  serviceName: volumeclaimstorageclass
  template:
    metadata:
      labels:
        app: app-alpha
    spec:
      containers:
      - image: registry.k8s.io/nginx-slim:0.8
        name: main
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: somestorageclass
