apiVersion: test.gatekeeper.sh/v1alpha1
kind: Suite
metadata:
  name: tls-optional
tests:
- cases:
  - assertions:
    - violations: "no"
    inventory: null
    name: example-allowed-tls-optional
    object: artifacts/alpha-01.yaml
  - assertions:
    - violations: "yes"
    inventory: null
    name: example-disallowed-tls-optional
    object: artifacts/beta-01.yaml
  constraint: constraint.yaml
  name: tls-optional
  template: template.yaml
