apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-interactive-tty
    k8s-ai-bench/expected: alpha
    k8s-ai-bench/inventory: "false"
    k8s-ai-bench/task: disallow-interactive
  name: resource-alpha-01
  namespace: gk-disallow-interactive
spec:
  containers:
  - image: nginx
    name: nginx
    stdin: false
    tty: false
