setup: setup.sh
cleanup: cleanup.sh
difficulty: medium
expect:
- contains: VIOLATING:.*resource-beta.*
  notContains: resource-alpha
script:
- prompt: 'Hey, can you check if I have any resources in the ''gk-test-010'' namespace
    that Container images can''t use the ''latest'' tag, except for certain images.?
    I need to make sure we''re following our internal rules.


    If you find any, list them in this format:

    VIOLATING: resource_name, resource_name


    Otherwise, just output:

    VIOLATING: none'
