apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  automountServiceAccountToken: false
  containers:
  - image: nginxinc/nginx-unprivileged:latest
    name: container-alpha
