apiVersion: v1
kind: Namespace
metadata:
  labels:
    k8s-ai-bench/expected: alpha
    k8s-ai-bench/inventory: "false"
    k8s-ai-bench/task: must-have-owner
    owner: user.agilebank.demo
  name: resource-alpha-01
