apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-beta
  name: resource-beta
spec:
  containers:
  - image: nginx
    name: container-beta
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: nginx
    name: container-beta-1
    volumeMounts:
    - mountPath: /cache2
      name: demo-vol
  volumes:
  - hostPath:
      path: /tmp
    name: cache-volume
  - emptyDir: {}
    name: demo-vol
