apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  containers:
  - image: nginx
    name: container-alpha
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: nginx
    name: container-alpha-1
    volumeMounts:
    - mountPath: /cache2
      name: demo-vol
  volumes:
  - emptyDir: {}
    name: cache-volume
  - emptyDir: {}
    name: demo-vol
