apiVersion: v1
kind: Pod
metadata:
  name: resource-beta
spec:
  containers:
  - image: nginx
    name: container-beta
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
      readOnly: true
  volumes:
  - hostPath:
      path: /tmp
    name: cache-volume
