apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    k8s-ai-bench/expected: beta
    k8s-ai-bench/inventory: "false"
    k8s-ai-bench/task: block-wildcard-ingress
  name: resource-beta-03
  namespace: gk-block-wildcard-ingress
spec:
  rules:
  - host: '*.example.com'
    http:
      paths:
      - backend:
          service:
            name: example
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: valid.example.com
    http:
      paths:
      - backend:
          service:
            name: example
            port:
              number: 80
        path: /
        pathType: Prefix
