apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-ai-bench/expected: beta
    k8s-ai-bench/inventory: "false"
    k8s-ai-bench/task: must-have-set-of-annotations
  name: resource-beta-01
  namespace: gk-must-have-set-of-annotations
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: foo
