apiVersion: v1
kind: Pod
metadata:
  labels:
    owner: me.agilebank.demo
  name: resource-beta
spec:
  containers:
  - image: nginx:latest
    name: container-beta
    resources:
      limits:
        cpu: 100m
        ephemeral-storage: 100Mi
        memory: 1Gi
  initContainers:
  - command:
    - sh
    - -c
    - exit 0
    image: nginx:latest
    name: init-container-beta
    resources:
      limits:
        cpu: 100m
        ephemeral-storage: 1Pi
        memory: 1Gi
